# Generated by Django 5.1.5 on 2025-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='long_term_guarantee_selected',
            field=models.BooleanField(default=False),
        ),
    ]
