# Generated by Django 5.1.4 on 2025-01-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristictype',
            name='suffix',
            field=models.CharField(blank=True, help_text="Optional suffix to display with the value, e.g., 'km/h', '%'.", max_length=20, null=True),
        ),
    ]
