# Generated by Django 5.1.4 on 2025-01-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, help_text='Store an SVG icon as a string', null=True),
        ),
    ]
