# Generated by Django 5.1.4 on 2025-01-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_characteristictype_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristictype',
            name='category',
        ),
        migrations.AddField(
            model_name='characteristictype',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='characteristics', to='products.category'),
        ),
    ]
