# Generated by Django 5.1.5 on 2025-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_name_af_remove_category_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='long_term_guarantee',
            field=models.BooleanField(default=False),
        ),
    ]
