# Generated by Django 5.1.5 on 2025-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_long_term_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='long_term_guarantee',
            field=models.BooleanField(default=False, help_text='Guarantee 24 mounth for products'),
        ),
    ]
