# Generated by Django 5.1.4 on 2025-01-19 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcomment_delete_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products.product'),
        ),
    ]
