# Generated by Django 5.1.4 on 2025-01-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productcomment_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomment',
            unique_together=set(),
        ),
    ]
