# Generated by Django 5.1.5 on 2025-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_category_long_term_guarantee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Price for a product in Kč", max_digits=10
            ),
        ),
    ]
