# Generated by Django 5.1.4 on 2025-01-31 13:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
